config/routes.rb
Quiztwo::Application.routes.draw do

  root 'dogs#index'

  resources :dogs

end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
	def index
		@dog = Dog.order("RANDOM()").first 
	end

	def new
		@dog = Dog.new
	end	

	def create
		Dog.create(dog_params)
		redirect_to root_path
	end

	private

	def dog_params
		params.require(:dog).permit(:saying)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/index.html.erb
<h1>Quiz Number Two</h1>
<br/>
<h2><%= @dog.saying %></h2>

<br/>
<br/>

<%= link_to 'Input', new_dog_path %>
<br/>
<br/>

<%= image_tag 'nooice.jpg' %>

app/views/dogs/new.html.erb
	<h2>Enter Something</h2>
<%= simple_form_for @dog do |f| %>
  <%= f.input :saying %>
  <br/>
  <%= f.submit 'Create' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiztwo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>